"""create table vaccine_card

Revision ID: 151f634bde3a
Revises:
Create Date: 2021-09-27 15:40:42.781213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151f634bde3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccine_card',
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('first_shot_date', sa.Date(), nullable=True),
    sa.Column('second_shot_date', sa.Date(), nullable=True),
    sa.Column('vaccine_name', sa.String(), nullable=False),
    sa.Column('health_unit_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cpf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccine_card')
    # ### end Alembic commands ###
